Feature/savings log
LittleKidogo/MoneyLog pull request #140
Opened 2018-07-16 18:48 UTC by br4inii

Fixes #27

## Proposed Changes

  -create savings log
  -update savings log
  -

2018-07-17 05:18 UTC, zacck commented
@br4inii  it seems like the code is broken please run `MIX_ENV=test mix test`

2018-07-17 05:41 UTC, zacck-zz requested changes
@br4inii  good work on this, however, we need a couple of changes to get this going

2018-07-17 05:41 UTC, zacck commented on priv/repo/migrations/20180716142600_create_savings_log.exs
> +    @doc """
hey @br4inii  this doc has to be outside the function

2018-07-17 05:41 UTC, zacck commented on priv/repo/migrations/20180716142600_create_savings_log.exs
> +      add :log_category_id, references(:budgets)
this should be referencing `LogCategories`

2018-07-19 18:37 UTC, zacck-zz requested changes
@br4inii  this is awesome excellent work looks clean!
Would it be possible for you to squash some of the earlier commits that are not relevant now?

2018-07-19 18:45 UTC, br4inii commented
@zacck am on it!!

2018-07-20 08:32 UTC, zacck-zz approved these changes
@br4inii  this is awesome work!

2018-07-20 08:36 UTC, merged