Feature/associate expenselog to logcategory
LittleKidogo/MoneyLog pull request #154
Opened 2018-08-01 10:06 UTC by WanjikuMac

Fixes #115 

## Proposed Changes

  -Associate the ExpenseLog to the LogCategory
  -
  -

2018-08-01 11:44 UTC, zacck-zz requested changes
Hey @WanjikuMac  this is awesome work! just a few changes to push it over the hill...

2018-08-01 11:44 UTC, zacck commented on lib/spender/using/expense_log.ex
> + @spec create_changeset(Budget.t(), map) :: Changeset.t()
Would you mind adding doc attributes to these functions?

2018-08-01 11:44 UTC, zacck commented on priv/repo/migrations/20180731180224_associate_expenselog_to_logcategory.exs
> +defmodule Spender.Repo.Migrations.AssociateExpenselogToLogcategory do
Would you mind adding a module doc and doc attributes here too

2018-08-02 18:11 UTC, zacck-zz approved these changes
Dope 🤙🏾

2018-08-02 18:11 UTC, zacck-zz approved these changes
Dope 🤙🏾

2018-08-03 13:11 UTC, r-coh approved these changes
Awsome.

2018-08-04 08:27 UTC, merged