Feature/rename budgets to moneylog
LittleKidogo/MoneyLog pull request #158
Opened 2018-08-03 20:50 UTC by br4inii

Fixes #112 

## Proposed Changes

  - rename budgets table to moneylog
  - 
  -

2018-08-04 04:47 UTC, zacck commented
@br4inii this is breaking due to #159

2018-08-04 04:58 UTC, zacck-zz requested changes
Wow @br4inii  this is a huge refactor, awesome awesome work!

2018-08-04 04:58 UTC, zacck commented on lib/spender/money_logs/budget.ex
> +  schema "moneylog" do
@br4inii  this should be `moneylogs`  the table name is usually the plural

2018-08-04 04:58 UTC, zacck commented on lib/spender/money_logs/owner.ex
> +    has_many :moneylog, Moneylog, on_delete: :delete_all
This too should be `moneylogs` since later you want to access them as `Owner.moneylogs`

2018-08-04 04:58 UTC, zacck commented on test/lib/spender_web/resolvers/owner_test.exs
> +      moneylog = insert_list(10, :moneylog, owner: owner)
This should be `moneylogs` too

2018-08-04 04:58 UTC, zacck commented on test/lib/spender_web/resolvers/owner_test.exs
> +        moneylog {
this should be `moneylogs`

2018-08-04 04:58 UTC, zacck commented on test/lib/spender_web/resolvers/owner_test.exs
> +      res = conn  |> get("/graphiql", AbsintheHelpers.query_skeleton(query,"moneylog"))
`moneylogs`

2018-08-04 04:58 UTC, zacck commented on test/lib/spender_web/resolvers/owner_test.exs
> +          "moneylog" => fetched_moneylog
`moneylogs`

2018-08-04 04:58 UTC, zacck commented on test/lib/spender_web/resolvers/owner_test.exs
> +          "moneylog" => fetched_moneylog
`fetched_moneylogs`

2018-08-04 04:58 UTC, zacck commented on test/lib/spender_web/resolvers/owner_test.exs
> +      assert Enum.count(fetched_moneylog) == Enum.count(moneylog)
`fetched_moneylogs`

2018-08-04 04:58 UTC, zacck commented on test/lib/spender_web/resolvers/owner_test.exs
> +    test "returns error when moneylog is nil", %{conn: conn, current_user: user} do
`moneylogs`

2018-08-04 05:56 UTC, br4inii commented
@zacck thanks mahn, you mean everywhere we refer to the schema should be `moneylogs` even if the schema is named `moneylog` !?

2018-08-04 05:59 UTC, zacck commented
@br4inii   no just the places I have reffered to in the review, some parts refer to a single `moneylog` and some parts refer to a list of `moneylogs`.

i.e the parts that were `Budget` become `Moneylog` and the parts that were `budgets` become `moneylogs`

2018-08-04 08:28 UTC, zacck commented
@br4inii  would you mind rebasing this on develop?

2018-08-05 21:56 UTC, zacck-zz approved these changes
Awesome work on this @br4inii

2018-08-05 21:56 UTC, merged

2018-08-05 22:37 UTC, br4inii commented
Thanks for the review @zacck